### ISSUE TITLE
Unable to compile subfixer

### ISSUE THREAD

**Issue by teras** [chetan-prime/subfixer#1]
Hello

When I am trying to compile it I get the following error:

```
subfixer.go:8:2: cannot find package "github.com/chetan-prime/subfixer/astisub" in any of:
	/usr/local/Cellar/go/1.13/libexec/src/github.com/chetan-prime/subfixer/astisub (from $GOROOT)
	/Users/teras/Sources/subfixer/packages/src/github.com/chetan-prime/subfixer/astisub (from $GOPATH)
```

I have macOS 10.14.6
go version go1.13 darwin/amd64

Any ideas?

**Comment by chetan-prime** [comment]
Hi there,
I've updated the source to latest.
Check if it works for you now. I believe it should fix your issue.
Also this is tested with the official google version of golang. I see you are using 1.13 so it should be fine.

**Comment by teras** [comment]
I seems to work now. Thank you
