### ISSUE TITLE
Package cannot be found

### ISSUE THREAD

**Issue by Forium777** [chetan-prime/subfixer#2]
Hello,
I tried to use your project, but when I try to build from make file I get the following error :      
``astisub/srt.go:10:2: cannot find package``

I tried to do ``go get github.com/pkg/errors``without success.

Tried on Windows from Cygwin and on macOS Big Sur arm64 (M1).
``go version go1.16.3 darwin/arm64``

Any idea?

Thanks.

**Comment by chetan-prime** [comment]
I don't see an issue here. The package https://github.com/pkg/errors exists and seems to work fine for me.
Make sure you have a recent enough version of Go compatible with it, something like Golang 1.10 or higher should work fine.
